### ISSUE TITLE
Unable to get update information Mac High Sierra

### ISSUE THREAD

**Issue by zebus3d** [overmindstudios/BlenderUpdater#13]
In mac 10.13.2 High Sierra get this error:

Dialog:
Unable to get update information

```
python3 BlenderUpdater.py
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "BlenderUpdater.py", line 663, in <module>
    main()
  File "BlenderUpdater.py", line 655, in main
    window = BlenderUpdater()
  File "BlenderUpdater.py", line 207, in __init__
    UpdateData = json.loads(Appupdate)
UnboundLocalError: local variable 'Appupdate' referenced before assignment
```

My temporal solution is:
`comment from line 201 to 214 looks like it does start well.`

**Comment by tobkum** [comment]
Just commited something, can you retry with the new BlenderUpdater.py and post the log here?

**Comment by zebus3d** [comment]
```
$ python3 BlenderUpdater.py
BlenderUpdater.py:141: SyntaxWarning: name 'appversion' is used prior to global declaration
  global appversion
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "BlenderUpdater.py", line 667, in <module>
    main()
  File "BlenderUpdater.py", line 659, in main
    window = BlenderUpdater()
  File "BlenderUpdater.py", line 209, in __init__
    UpdateData = json.loads(Appupdate)
UnboundLocalError: local variable 'Appupdate' referenced before assignment
```

**Comment by tobkum** [comment]
And the content of the BlenderUpdater.log that gets generated please :)

**Comment by zebus3d** [comment]
```
INFO 2018-04-04 14:10:20,596 - Running version 1.9
DEBUG 2018-04-04 14:10:20,596 - Constructing UI
DEBUG 2018-04-04 14:10:20,656 - No previous config found
ERROR 2018-04-04 14:10:23,332 - Unable to get update information from GitHub

```

**Comment by zebus3d** [comment]
you are using a try to create the Appupdate variable, this one does not initialize any value in Appupdate when it fails, so it gives the error later.

**Comment by tobkum** [comment]
That is weird, since it works on Win and Linux. Can you make sure that the following URL is reachable from your system

https://api.github.com/repos/overmindstudios/BlenderUpdater/releases/latest

It should output something like that:
![image](https://user-images.githubusercontent.com/16955378/38306996-9589a3a4-3812-11e8-801f-a313c276f13c.png)

**Comment by tobkum** [comment]
Interesting, seems that the default OSX ssl version does not match.
Found some comments here: https://github.com/kelproject/pykube/issues/80#issuecomment-280958538
and here: https://stackoverflow.com/a/49466649

**Comment by tobkum** [comment]
Could you try a `pip install 'requests[security]'` on your system for me?

**Comment by zebus3d** [comment]
Don't worry, something's wrong with my system. It's not a software bug.

**Comment by tobkum** [comment]
Alright, closing this issue. Thanks!

**Comment by zebus3d** [comment]
i have managed to avoid the problem by using requests.get instead of urllib.urlopen:

```
        # Check for new version on github
        try:
            Appupdate = requests.get("https://api.github.com/repos/overmindstudios/BlenderUpdater/releases/latest").text
            logger.info('Getting update info - success')
            UpdateData = json.loads(Appupdate)
            applatestversion = UpdateData['tag_name']
            logger.info('Version found online: ' + UpdateData['tag_name'])
            if StrictVersion(applatestversion) > StrictVersion(appversion):
                logger.info('Newer version found on Github')
                self.btn_newVersion.clicked.connect(self.getAppUpdate)
                self.btn_newVersion.setStyleSheet('background: rgb(73, 50, 20)')
                self.btn_newVersion.show()
        except Exception:
            QtWidgets.QMessageBox.critical(None, "Error", "Unable to get Github update information" )
            logger.error('Unable to get update information from GitHub')
```

**Comment by tobkum** [comment]
fixed, thanks!!!
